golioth/pouch

src/block.c, tests/pouch/uplink/src/uplink.c, tests/pouch/uplink/testcase.yaml
Clarify the format of the block header. Include the header in the configurable block size to simplify calculations. The header is sent on the wire, so including it in the configurable block size is more intuitive to the user. Previously, part, but not all, of the header was allocated as additional overhead.
=> block: Simplify header logic

examples/ble_gatt/Kconfig, examples/ble_gatt/src/main.c
Moves sync interval to Kconfig such that it can be configured at build time.
=> examples: ble_gatt: make sync interval configurable

.github/workflows/tests.yml, west-ncs.yml
Incoming additions around cryptography are significantly easier to implement on Nordic devices when using NCS than with raw zephyr. This adds an ncs manifest, so that we can run both.
=> Add NCS manifest

.github/workflows/tests.yml
This comes with 'uv' as a replacement for pip.
=> ci: bump Docker image to 0.17.0-SDK-v0

CMakeLists.txt, include/pouch/types.h, src/Kconfig, src/block.c, src/block.h, src/crypto.h, src/crypto_none.c, src/crypto_saead.c, src/downlink.c, src/downlink.h, src/header.c, src/header.cddl, src/header.h, src/pouch.c, src/saead/mbedtls_config.h, src/saead/session.c, src/saead/session.h, src/saead/uplink.c, src/saead/uplink.h, src/uplink.c, src/uplink.h, tests/pouch/uplink/prj.conf
Adds uplink SAEAD sessions, and a crypto_saead.c module.
This adds SAEAD support to the pouch header and config structure, adds some lifecycle functions to the crypto modules and shuffles the configuration ownership around a bit so that it makes more sense.
=> Encrypted uplink

examples/ble_gatt/src/main.c, include/pouch/transport/ble_gatt/peripheral.h, src/transport/ble_gatt/CMakeLists.txt, src/transport/ble_gatt/characteristics.ld, src/transport/ble_gatt/downlink_characteristic.c, src/transport/ble_gatt/golioth_ble_gatt_declarations.h, src/transport/ble_gatt/info.cddl, src/transport/ble_gatt/info_characteristic.c, src/transport/ble_gatt/peripheral.c, src/transport/ble_gatt/peripheral_int.h, src/transport/ble_gatt/server_cert_characteristic.c, src/transport/ble_gatt/uplink_characteristic.c
Changes the format of the info characteristic to flags and server cert serial number. This allows us to remove the init function for the attributes, as we have to construct the info structure before each read, in case any of the data changes. This simplifies the macro, setup and linker sections.
Renames the peripheral_create to init to reflect the lack of a destroy function, now that we don't have to allocate anything.
=> Use updated info characteristic

.github/workflows/tests.yml, examples/ble_gatt/Kconfig, examples/ble_gatt/src/main.c, src/transport/ble_gatt/info_characteristic.c
When Pouch is compiled without encryption support, the info characteristic failed to link due to an unresolved reference to `pouch_server_certificate_serial_get()`.
=> transport: ble_gatt: info: fix build for plaintext encryption

examples/ble_gatt/src/credentials.c
Printing as %x implicitly converts to unsigned. Negate value before
printing, so that meaningful error code is printed.
=> examples: ble_gatt: show mbedtls error as negative value

examples/ble_gatt/src/main.c
Certificate is passed as pointer (wrapped with 'struct pouch_cert') and
stored as such. Freeing certificate results in use-after-free.
Don't free certificate, so that allocated buffer contents are valid
through the lifetime of application.
=> examples: ble_gatt: don't free certificate

golioth_sdk/dispatch.c, lib/zcbor_utils/zcbor_utils.c, src/cert.c, src/saead/downlink.c, src/saead/session.c, src/saead/uplink.c, src/transport/ble_gatt/info_characteristic.c
Several pouch modules had their log level hardcoded in the registration macro. This shouldn't be the default, so this change removes all of those, except the ones in the example.
=> Remove hard coded log levels

Kconfig, golioth_sdk/Kconfig, golioth_sdk/dispatch.c, golioth_sdk/ota.c, golioth_sdk/ota_upper.c, golioth_sdk/settings.c, lib/zcbor_utils/zcbor_utils.c, src/cert.c, src/downlink.c, src/entry.c, src/saead/downlink.c, src/saead/session.c, src/saead/uplink.c, src/transport/ble_gatt/info_characteristic.c
Adds a CONFIG_POUCH_LOG_LEVEL kconfig setting that controls the log level for all pouch modules, and a CONFIG_GOLIOTH_LOG_LEVEL for the golioth_sdk modules.
=> Add log level settings

lib/pouch_ble_gatt_common/packetizer.c
This allows callers to detect when a packet has no payload without having to know the length of the toothfairy header.
=> packetizer: don't create 0 length payload packets

Kconfig, src/cert.c
Adds check for server certificate common name during verification.
Will need rebase on #76 before merge.
=> cert: check server certificate common name

examples/ble_gatt/prj.conf
Resolves golioth/firmware-issue-tracker#838
=> examples: ble_gatt: enable mcumgr parameters command

examples/ble_gatt/boards/nrf52_bsim.overlay
Define slot0 and slot1 partitiions, so that OTA requirements are met.
=> examples: ble_gatt: add 'nrf52_bsim'

src/transport/ble_gatt/server_cert_characteristic.c
Resolves golioth/firmware-issue-tracker#830
=> transport: ble_gatt: disconnect on server cert failure

examples/ble_gatt/src/fw_update.c
Without this fix, the Coverity workflow fails, because it builds with `CONFIG_LOG=n`.
=> examples: ble_gatt: fix build when CONFIG_LOG is disabled

src/saead/session.c
The blocksize is represented as a hexidecimal string during key agreement. There are (at least) two ways to represent each value that contains at least one alphabetic character because these characters can be either upper or lower case. We have determined that the canonical representation of hexadecimal numbers in strings will use upper case, so this commit updates the implementation to match.
Without this change, blocksizes greater than 512 (i.e. `log2(blocksize) >= 10`) would fail to decrypt on the cloud, due to different inputs to the key derivation function.
=> saead: session: canonicalize blocksize representation

src/downlink.c
`pouch_buf` is allocated in `pouch_dwnlink_start()` and possibly reallocated in `pouch_downlink_push()`. However, there was no final `buf_free()` call, so with the next `pouch_downlink_start()` there was a memory leak due to pointer override with new allocation.
Free `pouch_buf` in `pouch_downlink_finish()` and assing it to NULL, so next invocation of `pouch_downlink_start()` is not creating memory leak.
=> downlink: fix 'pouch_buf' memory leak

src/transport/ble_gatt/golioth_ble_gatt_declarations.h, src/transport/ble_gatt/uplink_characteristic.c, west.yml
Support using indications to send uplink. Explicit reads from the Gateway are still supported.
Resolves golioth/firmware-issue-tracker#845
=> Uplink indications
